ACADEMY_DATA_COLLECT_INFO=/academy/academy_message.json
ACCOUNT_LINK_CARD_DETAIL_API=/account_link/linked_accounts_card.json
ACCOUNT_LINK_CARD_INFO_API=/account_link/linked_accounts_card.json
ACCOUNT_LINK_REDIRECT_LINK_API=/account_link/redirect_url.json
AGENT_WITHDRAW_INFO_API=/info/agent_withdraw.html
AIRLINES_CODES_API=/airlines/airline_codes.json
AIRLINES_CONTACT_INFO=/airlines/airlines_contact.json
AIRLINES_VALIDATION_API=/airlines/validation.json
ALERT_BANNER_CDN_CONFIRM_API=/messages/action_required_card.json
AMOUNT_AND_PURPOSE_LIST_API=/ui/js/fonepay_amount_and_purpose_list.json
AMOUNT_LIST_API=/amount_list/amount_list.json
APPLICATION_CONFIG=/configs/application_config.json
AUTO_WITHDRAW_CONTENTS_CDN=autowithdraw/contents.json
BANK_TRANSFER_INFO_API=/info/bank_transfer.html
BLACKLIST_ITEM=/statement/blacklist.json
CARD_LOAD_INFO_API=/info/card_load_info.html
CASH_POINT_LOCATION_API=/cash_point/cashpoint_new.json
CDN_PRODUCT_INFO_API=/direct_topup/topup_v1.json
CDN_WEBVIEW=/ui/html/{product_code}.html
CHECK_DATA_PACK_STATUS_API=/datapack/datapack_v1.json
COLLEGE_LIST_API=/academy/college_fee_payment_v1.json
COMEDY_CHAMPION_INFO_API=/info/comedy_champion_information.html
CONTACT_US_CDN_PATH=/contact_us/contact_us.json
COOPERATIVE_BANK_LIST=/cooperative_withdraw/cooperative_bank_code_list.json
COUNCIL_SERVICE_API=/academy/council_service.json
CREDIT_CARD_API=/creditcard/creditcard.json
CREDIT_CARD_LOAD_FORM_DETAILS=/ui/js/fonepay_amount_and_purpose_list.json
CROSS_BORDER_NOTE=cross_border/note.json
CROSS_BORDER_NOTE_API=/esewa_gprs/cross_border/note.json
DIGITAL_DAKSHINA_CONFIG_CDN=/daksina/daksina.json
DISHHOME_DENOMINATION=/dishhome/dishhome.json
DOMESTIC_AIRLINES_DYNAMIC_FORM_MAPPING_API=/airlines/domestic_airlines_dynamic_form_mapping.json
DOMESTIC_AIRLINES_IMAGE_LIST_API=/airlines/domestic_flight_list.json
DOM_AIRLINES_PAN_DETAIL_UI_CONFIG=/airlines/airlines_pan_details_config.json
ESEWA_REMIT_LOCATION_API=/esewa_remit/esewa_remit.json
EXAM_FEE_API=/academy/exam_fee.json
FINHUB_CONFIG_URL=/finhub/finhub_config.json
FINHUB_DASHBOARD_ITEMS=/finhub/finhub_banner.json
FINHUB_ESEWA_LOAN_AGREEMENT_PDF=/finhub/finhub_esewa_pdf.json
FINHUB_PRODUCTS=/finhub/finhub_products.json
FLAG_NEPAL_API=/esewa_gprs/images/flag/img_flag_nepal.png
FORGOT_MPINYOUTUBE_API=/forgot_mpin/forgot_mpin.json
GET_CONFIG=/pay_circle/config.json
GET_EVENT_TYPE_COLOR_CODE=/calendar/event_type_color_code_in_minutes.json
GET_HGI_MICRO_INSURANCE_AMOUNT=/hgi/microinsurance_amount.json
GET_ONBOARDING=/pfm/expense_manager_onboarding.json
GET_REMINDER_TIME=/calendar/calendar_event_reminder_time.json
HGI_BRANCH_API=/insurance/hgi/branch.json
HGI_COVID19_AMOUNT_API=/hgi_covid19/hgi_covid19_amount.json
HGI_INSURANCE_TYPE_API=/insurance/hgi/insurance_type.json
HGI_POLICY_TYPE_API=/insurance/hgi/policy_type.json
IFLIX_VOUCHER_API=/iflix/iflix.json
KUKL_BRANCH_CODE_API=/ui/data/KUKLBranchCode.json
KYC_CONFIRMATION_FORCE_UPDATE=/kyc/kyc_confirmation_force_update.json
KYC_ENABLE_STATUS_CDN=/kyc/kyc_enable_status.json
KYC_FORCE_UPDATE=/kyc/kyc_force_update.json
KYC_LANDING_PAGE_INFO_LIST_CDN=/kyc/landing_page_list.json
KYC_LANDING_PAGE_POPUP_CDN=/kyc/landing_page_popup_list.json
LANDING_MESSAGES_API=/landing_page_products/landing_page/messages.json
LANDING_UTILITIES_API=/landing_page_products/landing_page/utilities.json
LOAD_CHASOUT_FORM_DETAILS=/ui/js/fonepay_amount_and_purpose_list.json
LOAD_FUND_API=/load_fund/load_fund_list_v2.json
LOAD_FUND_FORM_DETAILS=/ui/js/fonepay_amount_and_purpose_list.json
LOCAL_NOTIFICATIONS_CONFIG=/calendar/local_notifications_config.json
MANAGED_BOOKING_DISCLAIMER=/airlines/managed_booking_disclaimer.json
MERCHANT_BANKS_LIST_CDN_API=/ui/data/pcs_merchant_banker_code.json
MONTESSORI_LIST_API=/academy/montessori_fee_payment_v1.json
MY_PAYMENT_WELCOME_SHOWCASE_API=/my_payment/my_payment_v1.json
NEPAL_IDOL_INFORMATION_API=/nepal_idol/info.json
NEPAL_IDOL_INFO_API=/info/nepal_idol_info.html
NEW_BANNER_ITEMS_API=/landing_page_products/landing_page/banner_items.json
NICASIA_REMITTANCE_PURPOSE=/remittance/nicasia_pickup_purpose.json
OFFLINE_PAYMENT_CONFIG_CDN=/offline_payment/offline_payment_config.json
ONBOARDING=/fonepoints/fonepoint_onboarding.json
ONLINE_PG_EXAMS_API=/onlinepg/examlist_v1.json
OYO_HOTEL_LOCATION_API=/oyo/oyo.json
PARK_IMAGE_CDN=/park/park_dashboard.json
PARTNER_BANK_API=/partnerbanks/partnerbank.json
POST_TRANSACTION_BANNER_API=/banner/banner_post_transaction.json
PRABHU_TV_AMOUNT_API=/prabhutv/prabhutv.json
PRODUCT_CODE_INFO_API=/info/{product_code}.html
REFER_AND_EARN_INFO_API=/refer_and_earn/info.json
REMITTANCE_AGENT_RECEIVE_MONEY_INFO_API=/info/agent_remittance_receive_money.html
REMITTANCE_AGENT_SEND_MONEY_INFO_API=/info/agent_remittance_send_money.html
REMITTANCE_SERVICE_LIST_CDN_API=/esewa_gprs/remittance/remit_service.json
REMIT_DOCUMENT_TYPE_API=/remittance/remit_withdraw/document_type.json
REMIT_INCOME_SOURCE_API=/remittance/remit_withdraw/source_of_income.json
REMIT_PURPOSE_API=/remittance/remit_withdraw/purpose.json
REMIT_RECIEVE_MONEY_INFO_API=/info/remit_recieve_money.html
REMIT_RELATIONSHIP_API=/remittance/remit_withdraw/relationship.json
SAHAKARI_WITHDRAW_INFO_API=/info/sahakari_withdraw.html
SASTO_TICKET_BANNER_IMAGE_API=/banner/banner_airlines.json
SAVE_PAYMENT_WELCOME_CONTENT_API=/my_payment/save_payment_welcome_content.json
SAVING_ONBOARDING_API=/saving/saving_onboarding.json
SAVING_PLANS_API=/saving/saving_plan.json
SAVING_SUBSCRIPTION_INFO_API=/saving/saving_subscription.json
SCHOOL_LIST_API=/academy/school_fee_payment_v3.json
SCHOOL_SOFTWARE_LIST_API=/academy/school_software.json
SECONDARY_BALANCE_API=/landing_page_products/landing_page/secondary_balance_info.json
SIM_TV_DENOMINATION=/sim_tv/sim_tv.json
SNOWLAND_CDN=/snowland/snowland.json
STATEMENT_DEBOUNCE_TIME=/configs/app_config.json
STATEMENT_INFO=/statement/statement_message.json
STATEMENT_MESSAGE=/statement/statement_message.json
TAYAR_NEPAL_CDN_CONFIGS=/insurance/tayar_nepal_config.json
TERMS_AND_CONDITION=/terms_conditions/loan_subscription/terms_and_conditions.json
TERMS_AND_CONDITIONS=/terms_conditions/terms_and_conditions.json
TVRS_DISTRICT_AND_PROVINCES_API=/ui/data/districtsProvincesTrafficPayment.json
TVRS_FISCAL_YEAR=/ui/data/fiscalYear.json
VEHICLE_PROVINCE_CDN=vrs/vehicleDetails.json
VEHICLE_TYPE_MAP_API=/ui/data/vrsVehicleOfficeMap.json
VOTING_PROCESS_CONFIG_API=/vote/vote_process_config.json
VRS_CAPACITY_LIST_API=/vrs/capacity.json
YOUTUBE_VIDEO_ID=/ui/youtube_video_link/youtube_video_id.json
